# Generated by Django 4.0.2 on 2022-03-04 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='İsim', max_length=200, verbose_name='İsim')),
                ('surName', models.CharField(help_text='Soy isim', max_length=200, verbose_name='Soy isim')),
                ('description', models.TextField(help_text='İçerik', max_length=500, verbose_name='İçerik')),
                ('user', models.ForeignKey(blank=True, help_text='Kullanıcı', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
