# Generated by Django 4.0.2 on 2022-02-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostAPP', '0003_alter_modelpost_unique_id'),
        ('CommentAPP', '0002_alter_modelcomment_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='PostAPP.modelpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Post Beğeni',
                'verbose_name_plural': 'Post Beğenileri',
                'db_table': 'PostLikes',
            },
        ),
        migrations.CreateModel(
            name='ModelCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='CommentAPP.modelcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yorum Beğeni',
                'verbose_name_plural': 'Yorum Beğenileri',
                'db_table': 'CommentLikes',
            },
        ),
    ]
