# Generated by Django 4.0.2 on 2022-02-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPP', '0002_modelfollower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelfollower',
            options={'verbose_name': 'Takip', 'verbose_name_plural': 'Takip'},
        ),
        migrations.AlterModelTable(
            name='modelfollower',
            table='Follower',
        ),
    ]
