# Generated by Django 4.0.2 on 2022-02-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPP', '0004_modelfollower_private_alter_modelfollower_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfollower',
            name='private',
        ),
        migrations.AddField(
            model_name='modeluser',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Gizli Hesap mı'),
        ),
    ]
