# Generated by Django 4.0.2 on 2022-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPP', '0005_remove_modelfollower_private_modeluser_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeluser',
            name='biography',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Biyogrofi'),
        ),
    ]
