# Generated by Django 4.0.2 on 2022-02-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcomment',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterModelTable(
            name='modelcomment',
            table='Comments',
        ),
    ]
