# Generated by Django 4.0.2 on 2022-02-14 17:34

import CommentAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentAPP', '0002_alter_modelcomment_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcomment',
            name='unique_id',
            field=models.CharField(blank=True, default=CommentAPP.models.create_new_ref_number, editable=False, max_length=100, unique=True),
        ),
    ]
