# Generated by Django 4.0.2 on 2022-02-08 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CommentAPP', '0002_alter_modelcomment_options_alter_modelcomment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcomment',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
    ]
