# Generated by Django 4.0.2 on 2022-02-07 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpost',
            options={'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.AddField(
            model_name='modelpost',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='images',
            field=models.FileField(upload_to='Posts'),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='modelpost',
            table='Posts',
        ),
        migrations.DeleteModel(
            name='ModelPostImages',
        ),
    ]
