# Generated by Django 4.0.2 on 2022-02-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAPP', '0002_alter_modelpost_options_modelpost_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='Posts'),
        ),
    ]
