# Generated by Django 4.0.2 on 2022-02-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostAPP', '0002_alter_modelpost_user_alter_modelpostimages_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpost',
            name='images',
        ),
    ]
