# Generated by Django 4.0.2 on 2022-02-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAPP', '0003_alter_modelpost_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Posts'),
        ),
    ]
