# Generated by Django 4.0.2 on 2022-02-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAPP', '0003_alter_modelpost_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
