# Generated by Django 4.0.2 on 2022-02-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostAPP', '0004_modelpost_images_delete_modelpostimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpost',
            options={'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderiler'},
        ),
        migrations.AlterModelTable(
            name='modelpost',
            table='Posts',
        ),
    ]
