# Generated by Django 4.0.2 on 2022-02-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelnotification',
            options={'verbose_name': 'Bildirim', 'verbose_name_plural': 'Bildirimler'},
        ),
        migrations.AlterModelOptions(
            name='modelrequest',
            options={'verbose_name': 'İstek', 'verbose_name_plural': 'İstekler'},
        ),
        migrations.AlterModelTable(
            name='modelnotification',
            table='Notifications',
        ),
        migrations.AlterModelTable(
            name='modelrequest',
            table='Requests',
        ),
    ]
