# Generated by Django 4.0.2 on 2022-02-15 20:59

import NotificationAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NotificationAPP', '0003_modelnotification_createddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnotification',
            name='unique_id',
            field=models.CharField(default=NotificationAPP.models.create_new_ref_number, editable=False, max_length=30, unique=True),
        ),
    ]
