# Generated by Django 4.0.2 on 2022-02-08 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostAPP', '0003_alter_modelpost_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savedDate', models.DateTimeField(auto_now_add=True, verbose_name='Kaydetme Tarihi')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostAPP.modelpost', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedposts', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kaydedilmiş Post',
                'verbose_name_plural': 'Kaydedilmiş Postlar',
                'db_table': 'SavedPosts',
                'ordering': ('-savedDate',),
            },
        ),
    ]
