# Generated by Django 4.0.2 on 2022-02-08 19:16

import StoryAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstory',
            name='unique_id',
            field=models.CharField(default=StoryAPP.models.create_new_ref_number, editable=False, max_length=35, unique=True),
        ),
    ]
