# Generated by Django 4.0.2 on 2022-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryAPP', '0002_modelstory_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstory',
            name='createdDate',
            field=models.DateTimeField(),
        ),
    ]
