# Generated by Django 4.0.2 on 2022-02-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryAPP', '0003_alter_modelstory_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstory',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
