# Generated by Django 4.0.2 on 2022-02-14 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StoryAPP', '0007_modelstoryread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstoryread',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeingusers', to='StoryAPP.modelstory', verbose_name='Hikaye'),
        ),
        migrations.AlterField(
            model_name='modelstoryread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gören Kullanıcı'),
        ),
    ]
