# Generated by Django 4.0.2 on 2022-02-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryAPP', '0008_alter_modelstoryread_story_alter_modelstoryread_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelstoryread',
            table='StoryRead',
        ),
    ]
