# Generated by Django 4.0.2 on 2022-02-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoryAPP', '0009_alter_modelstoryread_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=64)),
                ('resource', models.CharField(max_length=128)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='StoryAPP.policy')),
            ],
        ),
    ]
